### ISSUE TITLE
pycld2 crashes the dev container

### ISSUE THREAD

**Issue by jankounchained** [centre-for-humanities-computing/danish-foundation-models#203]
I tried to build DFM's [docker image](https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/centre-for-humanities-computing/danish-foundation-models/), but it crashes after attempting to install `pycld2` (a dependency of `dolma`).

One reason for this seems to be that `pycld2` uses an ancient version of `wheel` (see attempted solution 3 bellow).  
Secondly, for some reason I can't reproduce the problem trying to install `pycld2` on my mac. It only happens inside the container (see attempted solution 2).

### Reproduce the problem

```
docker build --pull -f "Dockerfile.dev" -t danishfoundationmodels:latest "."
```

### Error log

```
#0 553.0 Successfully built kenlm dfm langdetect antlr4-python3-runtime dolma psutil
#0 553.0 Failed to build pycld2
#0 553.0 ERROR: Could not build wheels for pycld2, which is required to install pyproject.toml-based projects
#0 553.0 
#0 553.0 [notice] A new release of pip is available: 23.2.1 -> 23.3.1
#0 553.0 [notice] To update, run: pip install --upgrade pip
#0 554.3 make: *** [makefile:2: install] Error 1
------
Dockerfile-with-features:29
--------------------
  27 |     COPY makefile ./
  28 |     COPY pyproject.toml ./
  29 | >>> RUN make install
  30 |     
  31 |     # Install the app
--------------------
error: failed to solve: process "/bin/sh -c make install" did not complete successfully: exit code: 2
[565799 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.54.1-1702456006031/Dockerfile-with-features -t vsc-danish-foundation-models-3e5417e2964e641d8bc74fa394a256a8b59a2a017ddd51dc681c353333b82dce --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.54.1-1702456006031 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /workspaces/danish-foundation-models
[565799 ms]     at Y$ (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:463:1860)
[565799 ms]     at runMicrotasks (<anonymous>)
[565799 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[565799 ms]     at async Fw (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1831)
[565800 ms]     at async $J (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:608)
[565800 ms]     at async tAA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[565800 ms]     at async CC (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[565800 ms]     at async NeA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[565800 ms]     at async MeA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[565814 ms] Exit code 1
[565814 ms] Start: Run: docker rm -f 866a32134d554ec578dd17af7a2c305cffc7bcd78ac45abb62bcc934b58f424a
[565816 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-70233fba-1a74-4b6c-b8ee-bd88bfef87071702455999465 --workspace-folder /workspaces/danish-foundation-models --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/centre-for-humanities-computing/danish-foundation-models/ --id-label vsch.local.repository.volume=danish-foundation-models-dd6ae89797d266bcdc0cd2185a9c4b322aa65811dacc9d3db9d1579bb4acfd81 --id-label vsch.local.repository.folder=danish-foundation-models --id-label devcontainer.config_file=/workspaces/danish-foundation-models/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/danish-foundation-models/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-ea410059-a530-4350-8ae0-5502c7976dcc.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=danish-foundation-models-dd6ae89797d266bcdc0cd2185a9c4b322aa65811dacc9d3db9d1579bb4acfd81,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root
[565816 ms] Exit code 1
[565894 ms] Container server terminated (code: 137, signal: null).
```

### Attempted solutions
**1**
edit `Dockerfile.dev` so that it doesn't install python dependencies, then try to install dolma again
```
docker run -it danishfoundationmodels bash
pip install "dolma[pii,code]@git+https://github.com/allenai/dolma.git@28727302a34225f4ce70ce97940cb18ad9a91583"
pip install pycld2
```
this doesn't work, same problem.

**2**
install pycld2 on my mac (python 3.11.6).
works no problem.

**3**
run the container.
install a `pycld2` branch that bumped the version of wheel.
```
docker run -it danishfoundationmodels bash
pip install "git+https://github.com/aboSamoor/pycld2.git@dependabot/pip/wheel-0.38.1"
```
works!

### solutions?
- ~add `"git+https://github.com/aboSamoor/pycld2.git@dependabot/pip/wheel-0.38.1"` to our dependencies?~
- then dolma will still try to install the broken `pycld2` from pip. We could fork `dolma` and fix the dependency there for now?

**Comment by KennethEnevoldsen** [comment]
@peterbjorgensen is that an issue you have had as well?

**Comment by MartinBernstorff** [comment]
`553.0 ERROR: Could not build wheels for pycld2, which is required to install pyproject.toml-based projects`

Huh, surprised that manually installing dolma doesn't work, since the above indicates installing around the `pyproject.toml` should work. 

Looks like all we need is for dolma to update their `pycld2` dependency, right? :-)

**Comment by peterbjorgensen** [comment]
Weirdly `sudo docker build --pull -f "Dockerfile.dev" -t danishfoundationmodels:latest "."` works on my laptop.

I don't have VS code, so I haven't tested it that way, but Github also builds the docker image succesfully on every commit, right?

**Comment by MartinBernstorff** [comment]
> Weirdly `sudo docker build --pull -f "Dockerfile.dev" -t danishfoundationmodels:latest "."` works on my laptop.
> 
> I don't have VS code, so I haven't tested it that way, but Github also builds the docker image succesfully on every commit, right?

Yep, it builds on commit! But on x64, so perhaps its an ARM issue?

@peterbjorgensen Can you build without sudo? Is it on ARM?
@jankounchained Building on ARM or x64?

**Comment by MartinBernstorff** [comment]
Either way, if dolma can update their release to include `pcld2` with prebuilt wheels that work on @jankounchained's laptop, that seems like the best move?

**Comment by peterbjorgensen** [comment]
I can't build any docker image without sudo. According to arch wiki adding my normal user to the `docker` group is equivalent to `root` access, so I need sudo to run anything docker related.
I am on x64 hardware.
Dolma is already using the latest official release of `pycld2`. So `pycld2` needs to get fixed upstream, but maybe it's archived because pycld3 exists (but is more broken buildwise). We can always fork `pycld2` and fix it.

**Comment by MartinBernstorff** [comment]
Hmm, if its arm, `pycld2` might also only build wheels for Apple ARM, not `aarch64`. 

I get the same issue when trying to build on my Apple ARM machine:

```
#0 228.0 Successfully built kenlm dfm langdetect antlr4-python3-runtime dolma psutil
#0 228.0 Failed to build pycld2
#0 228.0 ERROR: Could not build wheels for pycld2, which is required to install pyproject.toml-based projects
#0 228.0 
#0 228.0 [notice] A new release of pip is available: 23.2.1 -> 23.3.1
#0 228.0 [notice] To update, run: pip install --upgrade pip
#0 229.3 make: *** [makefile:2: install] Error 1
------
Dockerfile-with-features:29
--------------------
  27 |     COPY makefile ./
  28 |     COPY pyproject.toml ./
  29 | >>> RUN make install
  30 |     
  31 |     # Install the app
--------------------
```

If we can get `pcld2` to build `aarch64` wheels, that should fix it. Unsure whether that's the best path, though.

**Comment by KennethEnevoldsen** [comment]
I added a few tags here. It seems like it is a known issue that should not be closed, but we are also not gonna fix it atm.

**Comment by peterbjorgensen** [comment]
If it makes the whole project uninstallable, we could decide to drop the `cld2` tagger or make it optional. According to this website fasttext seems to be pretty good (which we also have for language identification).
https://modelpredict.com/language-identification-survey

**Comment by KennethEnevoldsen** [comment]
Seems like there is a huge gap between cld2 fasttext. Any good reasons for cld2 which I am missing?

**Comment by MartinBernstorff** [comment]
Memory usage perhaps?

![image](https://github.com/centre-for-humanities-computing/danish-foundation-models/assets/8526086/b01744c8-2c93-44ea-819f-1d3158ef2da2)

I have no idea whether that's important at the level of concurrency we'll be processing, though. Would have to make a back-of-the-envelope calc for that.

**Comment by peterbjorgensen** [comment]
The new version of dolma (1.0.0) now uses https://pypi.org/project/LTpycld2/ which is a drop-in replacement of pycld2, but works on Apple silicon.
